### ISSUE TITLE
register() error: "Missing required service info."

### ISSUE THREAD

**Issue by PTS93** [vstirbu/ZeroConf#14]
When I try to register a new service I get the above error. The error that triggers is in:
```
if (obj != null) {
	...
} else {
	callbackContext.error("Missing required service info.");
	return false;
}
```
https://github.com/vstirbu/ZeroConf/blob/master/src/android/ZeroConf.java#L109

I tried to debug this a little (close to zero experience with Java) but even if I hardcode the function arguments (https://github.com/vstirbu/ZeroConf/blob/master/src/android/ZeroConf.java#L95-L98) and let the if statement always be true the application just force quits when it launches.

**Comment by vstirbu** [comment]
Can you provide the JavaScript snippet where you call the plugin? Also information about your environment would be helpful, e.g. Android and Cordova version. Thanks!

**Comment by PTS93** [comment]
Oh I'm sorry I thought I added all that.
I'm running Cordova 5.3.3 and using Crosswalk webview plugin if that matters (not the old version that modified cordova) on Android 4.3.
I call it like this: `ZeroConf.register("_http._tcp.local.", "testService", 8080, "hello");`

**Comment by vstirbu** [comment]
And this [condition](https://github.com/vstirbu/ZeroConf/blob/master/src/android/ZeroConf.java#L94) is always true when you hardcode the values?

**Comment by PTS93** [comment]
Correct, looking like this:
``` JS
//JSONObject obj = args.optJSONObject(0);
			if (true) {
				final String type = "_http._tcp.local.";
				final String name = "testService";
				final int port = 8080;
				final String text = "hello";
```

**Comment by vstirbu** [comment]
Can you post the part of the log where it crashes?

**Comment by PTS93** [comment]
logcat gives me this:
I/chromium(28270): [INFO:CONSOLE(18)] "Initialized the NfcPlugin", source: file:///android_asset/www/plugins/com.chariotsolutions.nfc.plugin/www/phonegap-nfc.js (18)
E/chromium(28270): [ERROR:runtime_javascript_dialog_manager.cc(69)] Not implemented reached in virtual void xwalk::RuntimeJavaScriptDialogManager::ResetDialogState(content::WebContents*)

The nfc plugin is starting just fine and then I guess it tries to initalize ZeroConf.

Outside the app I get this in logcat:

E/AndroidRuntime(27763): Process: net.service.sample, PID: 27763
W/ActivityManager(  593):   Force finishing activity net.service.sample/.MainActivity
D/NfcPlugin(27763): Enabling plugin Intent { act=android.intent.action.MAIN flg=0x10000000 cmp=net.service.sample/.MainActivity }
D/NfcPlugin(27763): parseMessage Intent { act=android.intent.action.MAIN flg=0x10000000 cmp=net.service.sample/.MainActivity }
I/ActivityManager(  593): Process net.service.sample (pid 27763) has died.

**Comment by vstirbu** [comment]
This output is not enough for figuring out what the problem might be.

You could try to make a minimal app that uses only this plugin. It would help narrow done the source of the problem.

**Comment by PTS93** [comment]
I thought so, I created a new project with nothing but the plugin in it and the ZeroConfig.create(...) line in `deviceready`
The log should be more useful, see the fatal exception near the end:
``` bash
I/ActivityManager(  593): Start proc com.zeroconf.example for activity com.zeroconf.example/.MainActivity: pid=25721 uid=10096 gids={50096, 3003}
D/ActivityThread(25721): handleBindApplication:com.zeroconf.example
D/ActivityThread(25721): setTargetHeapUtilization:0.75
D/ActivityThread(25721): setTargetHeapMinFree:2097152
V/WebViewChromiumFactoryProvider(25721): Binding Chromium to main looper Looper (main, tid 1) {41b53cc0}
I/LibraryLoader(25721): Expected native library version number "",actual native library version number ""
I/chromium(25721): [INFO:library_loader_hooks.cc(116)] Chromium logging enabled: level = 0, default verbosity = 0
I/BrowserStartupController(25721): Initializing chromium process, renderers=0
E/AudioManagerAndroid(25721): BLUETOOTH permission is missing!
I/Adreno-EGL(25721): <qeglDrvAPI_eglInitialize:320>: EGL 1.4 QUALCOMM build: _msm8960_kk_2.7__release_AU ()
I/Adreno-EGL(25721): OpenGL ES Shader Compiler Version: 20.00.01
I/Adreno-EGL(25721): Build Date: 11/07/13 Thu
I/Adreno-EGL(25721): Local Branch: klp
I/Adreno-EGL(25721): Remote Branch: quic/hammerhead_klp
I/Adreno-EGL(25721): Local Patches: NONE
I/Adreno-EGL(25721): Reconstruct Branch: NOTHING
W/chromium(25721): [WARNING:proxy_service.cc(890)] PAC support disabled because there is no system implementation
I/dalvikvm(25721): Could not find method android.webkit.CookieManager.setAcceptThirdPartyCookies, referenced from method org.apache.cordova.engine.SystemCookieManager.<init>
W/dalvikvm(25721): VFY: unable to resolve virtual method 149: Landroid/webkit/CookieManager;.setAcceptThirdPartyCookies (Landroid/webkit/WebView;Z)V
D/dalvikvm(25721): VFY: replacing opcode 0x6e at 0x0016
I/dalvikvm(25721): Could not find method android.webkit.CookieManager.flush, referenced from method org.apache.cordova.engine.SystemCookieManager.flush
W/dalvikvm(25721): VFY: unable to resolve virtual method 144: Landroid/webkit/CookieManager;.flush ()V
D/dalvikvm(25721): VFY: replacing opcode 0x6e at 0x0008
W/dalvikvm(25721): VFY: unable to find class referenced in signature (Landroid/webkit/ClientCertRequest;)
W/dalvikvm(25721): VFY: unable to find class referenced in signature (Landroid/webkit/ClientCertRequest;)
I/dalvikvm(25721): Could not find method android.webkit.WebViewClient.onReceivedClientCertRequest, referenced from method org.apache.cordova.engine.SystemWebViewClient.onReceivedClientCertRequest
W/dalvikvm(25721): VFY: unable to resolve virtual method 202: Landroid/webkit/WebViewClient;.onReceivedClientCertRequest (Landroid/webkit/WebView;Landroid/webkit/ClientCertRequest;)V
D/dalvikvm(25721): VFY: replacing opcode 0x6f at 0x001a
W/dalvikvm(25721): VFY: unable to find class referenced in signature (Landroid/webkit/PermissionRequest;)
I/dalvikvm(25721): Could not find method android.webkit.PermissionRequest.getResources, referenced from method org.apache.cordova.engine.SystemWebChromeClient.onPermissionRequest
W/dalvikvm(25721): VFY: unable to resolve virtual method 160: Landroid/webkit/PermissionRequest;.getResources ()[Ljava/lang/String;
D/dalvikvm(25721): VFY: replacing opcode 0x6e at 0x000d
I/dalvikvm(25721): Could not find method android.webkit.WebChromeClient$FileChooserParams.createIntent, referenced from method org.apache.cordova.engine.SystemWebChromeClient.onShowFileChooser
W/dalvikvm(25721): VFY: unable to resolve virtual method 165: Landroid/webkit/WebChromeClient$FileChooserParams;.createIntent ()Landroid/content/Intent;
D/dalvikvm(25721): VFY: replacing opcode 0x6e at 0x0000
V/ZeroConf(25721): Initialized
D/AudioManagerAndroid(25721): ==> onReceive: s=0, m=0, n=h2w, sb=true
D/AudioManagerAndroid(25721): reportUpdate: state=0, devices=[Speakerphone, Headset earpiece]
D/OpenGLRenderer(25721): Enabling debug mode 0
W/AwContents(25721): nativeOnDraw failed; clearing to background color.
I/ActivityManager(  593): Displayed com.zeroconf.example/.MainActivity: +486ms
I/Timeline(  593): Timeline: Activity_windows_visible id: ActivityRecord{41abcdf8 u0 com.zeroconf.example/.MainActivity t44} time:52964644
W/AwContents(25721): nativeOnDraw failed; clearing to background color.
I/Timeline(25721): Timeline: Activity_idle id: android.os.BinderProxy@41b553b8 time:52964665
D/JsMessageQueue(25721): Set native->JS mode to OnlineEventsBridgeMode
I/chromium(25721): [INFO:CONSOLE(48)] "Received Event: deviceready", source: file:///android_asset/www/js/index.js (48)
W/dalvikvm(25721): threadid=23: thread exiting with uncaught exception (group=0x415d9ce0)
E/AndroidRuntime(25721): FATAL EXCEPTION: pool-1-thread-2
E/AndroidRuntime(25721): Process: com.zeroconf.example, PID: 25721
E/AndroidRuntime(25721): java.lang.NullPointerException
E/AndroidRuntime(25721): 	at com.triggertrap.ZeroConf.register(ZeroConf.java:180)
E/AndroidRuntime(25721): 	at com.triggertrap.ZeroConf.access$200(ZeroConf.java:44)
E/AndroidRuntime(25721): 	at com.triggertrap.ZeroConf$3.run(ZeroConf.java:105)
E/AndroidRuntime(25721): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(25721): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(25721): 	at java.lang.Thread.run(Thread.java:841)
W/ActivityManager(  593):   Force finishing activity com.zeroconf.example/.MainActivity
I/Timeline(  959): Timeline: Activity_idle id: android.os.BinderProxy@41a35088 time:52965268
E/libEGL  (25721): call to OpenGL ES API with no current context (logged once per thread)
I/Process (25721): Sending signal. PID: 25721 SIG: 9
W/IInputConnectionWrapper(25721): showStatusIcon on inactive InputConnection
E/WifiService(  593): Multicaster binderDied
I/ActivityManager(  593): Process com.zeroconf.example (pid 25721) has died.
```

**Comment by PTS93** [comment]
Here also the project tar.gz. It also contains the compiled apks (zeroconf_example/platforms/android/build/outputs/apk/).
http://www.filedropper.com/zeroconfexampletar

**Comment by vstirbu** [comment]
The error originates in [jmdns](http://sourceforge.net/projects/jmdns/) library.

> E/AndroidRuntime(25721):    at com.triggertrap.ZeroConf.register(ZeroConf.java:180)

The version that is bundled with this plugin is a quite old. Try to compile it again as a jar and add it to your project.

**Comment by vstirbu** [comment]
Can you check with this jar: http://search.maven.org/remotecontent?filepath=javax/jmdns/jmdns/3.4.1/jmdns-3.4.1.jar

**Comment by PTS93** [comment]
Unfortunately the error persists with the updated jar. I removed and readded the android platform to be sure its updated.

**Comment by vstirbu** [comment]
remove the plugin and add it again. the new version works as expected.

**Comment by PTS93** [comment]
Oh indeed, re-cloning did the job. Thanks a lot for your help!
