### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by creat-or** [vstirbu/ZeroConf#15]
Hi! When I try to install the plugin I get the following error:

```
cordova plugin add https://github.com/vstirbu/ZeroConf --verbose
Calling plugman.fetch on plugin "https://github.com/vstirbu/ZeroConf"
Fetching plugin "https://github.com/vstirbu/ZeroConf" via git clone
Cloning repository via git-clone command: git clone "https://github.com/vstirbu/ZeroConf" "/var/folders/40/bq9qyb914gn2hz8nfrt5lm5r0000gn/T/git/1446463105538"
Copying fetched plugin over "/Applications/MAMP/htdocs/flatout/flatout_ionic/plugins/cordova-zeroconf-plugin"...
Plugin "cordova-zeroconf-plugin" fetched.
Calling plugman.install on plugin "/Applications/MAMP/htdocs/flatout/flatout_ionic/plugins/cordova-zeroconf-plugin" for platform "android" with options "{"cli_variables":{},"browserify":false,"link":false,"pluginInfoProvider":{"_cache":{"/Applications/MAMP/htdocs/flatout/flatout_ionic/plugins/cordova-zeroconf-plugin":{"filepath":"/var/folders/40/bq9qyb914gn2hz8nfrt5lm5r0000gn/T/git/1446463105538/plugin.xml","dir":"/Applications/MAMP/htdocs/flatout/flatout_ionic/plugins/cordova-zeroconf-plugin","_et":{"_root":{"_id":374,"tag":"plugin","attrib":{"xmlns":"http://apache.org/cordova/ns/plugins/1.0","xmlns:android":"http://schemas.android.com/apk/res/android","id":"cordova-zeroconf-plugin","version":"1.2.0"},"text":"\n    ","tail":null,"_children":[{"_id":375,"tag":"engines","attrib":{},"text":"\n        ","tail":"\n\n    ","_children":[{"_id":376,"tag":"engine","attrib":{"name":"cordova","version":">=3.0.0"},"text":"","tail":"\n    ","_children":[]}]},{"_id":377,"tag":"name","attrib":{},"text":"ZeroConf","tail":"\n    ","_children":[]},{"_id":378,"tag":"description","attrib":{},"text":"ZeroConf plugin for Cordova/Phonegap","tail":"\n    ","_children":[]},{"_id":379,"tag":"author","attrib":{},"text":"Vlad Stirbu","tail":"\n    ","_children":[]},{"_id":380,"tag":"keywords","attrib":{},"text":"zeroconf","tail":"\n    ","_children":[]},{"_id":381,"tag":"license","attrib":{},"text":"MIT","tail":"\n\n    ","_children":[]},{"_id":382,"tag":"js-module","attrib":{"src":"www/ZeroConf.js","name":"zeroconf"},"text":"\n        ","tail":"\n\n    ","_children":[{"_id":383,"tag":"clobbers","attrib":{"target":"ZeroConf"},"text":"","tail":"\n    ","_children":[]}]},{"_id":384,"tag":"platform","attrib":{"name":"android"},"text":"\n\n        ","tail":"\n    ","_children":[{"_id":385,"tag":"config-file","attrib":{"target":"AndroidManifest.xml","parent":"/manifest"},"text":"\n            ","tail":"\n\n        ","_children":[{"_id":386,"tag":"uses-permission","attrib":{"android:name":"android.permission.CHANGE_WIFI_MULTICAST_STATE"},"text":"","tail":"\n            ","_children":[]},{"_id":387,"tag":"uses-permission","attrib":{"android:name":"android.permission.INTERNET"},"text":"","tail":"\n\t\t\t      ","_children":[]},{"_id":388,"tag":"uses-permission","attrib":{"android:name":"android.permission.ACCESS_WIFI_STATE"},"text":"","tail":"\n        ","_children":[]}]},{"_id":389,"tag":"config-file","attrib":{"target":"res/xml/config.xml","parent":"/*"},"text":"\n            ","tail":"\n\n        ","_children":[{"_id":390,"tag":"feature","attrib":{"name":"ZeroConf"},"text":"\n                ","tail":"\n        ","_children":[{"_id":391,"tag":"param","attrib":{"name":"android-package","value":"com.triggertrap.ZeroConf"},"text":"","tail":"\n                ","_children":[]},{"_id":392,"tag":"param","attrib":{"name":"onload","value":"true"},"text":"","tail":"\n            ","_children":[]}]}]},{"_id":393,"tag":"framework","attrib":{"src":"javax.jmdns:jmdns:+"},"text":"","tail":"\n\n        ","_children":[]},{"_id":394,"tag":"source-file","attrib":{"src":"src/android/ZeroConf.java","target-dir":"src/com/triggertrap"},"text":"","tail":"\n\n    ","_children":[]}]},{"_id":395,"tag":"info","attrib":{},"text":"","tail":"\n","_children":[]}]}},"id":"cordova-zeroconf-plugin","version":"1.2.0","name":"ZeroConf","description":"ZeroConf plugin for Cordova/Phonegap","license":"MIT","keywords":["zeroconf"],"info":""}},"_getAllCache":{}}}"
Installing "cordova-zeroconf-plugin" for android
Running command: /Applications/MAMP/htdocs/flatout/flatout_ionic/platforms/android/cordova/version
Command finished with error code 0: /Applications/MAMP/htdocs/flatout/flatout_ionic/platforms/android/cordova/version
Install start for "cordova-zeroconf-plugin" on android.
Beginning processing of action stack for android project...
Parsing android project files...
Installing Android library: javax.jmdns:jmdns:+
Error during processing of action! Attempting to revert...
Failed to install 'cordova-zeroconf-plugin':TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:422:13)
    at module.exports.framework.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:139:35)
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:67:25)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:575:20)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:335:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:422:13)
    at module.exports.framework.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:139:35)
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:67:25)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:575:20)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:335:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
```
System Info:
Cordova CLI: 4.3.0
OS: Mac OS X El Capitan

**Comment by vstirbu** [comment]
The latest version of the plugin works with `cordova-cli` 5 or newer.

Looks like the 4.3 is not able to handle maven dependencies. Can you try to install version 1.1.1 as that one has the jmdns.jar dependency bundled? Lets see what it happens...

**Comment by creat-or** [comment]
Thank you, that worked!

**Comment by vstirbu** [comment]
Btw, do you have maven installed on your system?

**Comment by creat-or** [comment]
```
mvn -v
Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c; 2015-03-13T21:10:27+01:00)
Maven home: /usr/local/Cellar/maven/3.3.1/libexec
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.1", arch: "x86_64", family: "mac"
```

**Comment by vstirbu** [comment]
Ok. Docs updated for early than cordova 5.
